apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: continuously-running-console
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:MaxBurgersSkyworkz/poc-Wehkamp-ArgoCD-Deployments.git
    targetRevision: HEAD
    path: deployments/continuously-running-console
  destination:
    server: "https://kubernetes.default.svc"
    namespace: continuously-running-console-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true